const Conversation = require('../models/Conversation');
const Mood = require('../models/Mood');
const { OpenAI } = require('openai');
const { Pinecone } = require('@pinecone-database/pinecone');
const axios = require('axios');
const FormData = require('form-data');
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize Arize Phoenix Global Config
const PHOENIX_ENDPOINT = process.env.PHOENIX_COLLECTOR_ENDPOINT || 'http://localhost:6006';

// Safety filter keywords
const EMERGENCY_KEYWORDS = [
  'suicide', 'kill myself', 'end my life', 'want to die', 'self harm', 'hurt myself',
  'cut myself', 'overdose', 'jump off', 'hang myself', 'not worth living',
  'better off dead', 'end it all', 'can\'t go on', 'taking my life',
  '108', '104', '112', 'ambulance', 'pcr'
];

const HARMFUL_CONTENT = [
  'violence', 'self-medication', 'illegal drugs', 'alcohol abuse'
];

// AI Provider Instances
let openai = null;
let genAI = null;
let geminiModel = null;
let aiInitialized = false;

/**
 * INITIALIZE AI SERVICES
 * Tier 1: Gemini (Cloud)
 * Tier 2: NVIDIA NIM (Cloud) 
 * Supports split keys for Chat and Embeddings.
 */
function initializeAI() {
  try {
    const nvChatKey = process.env.NVIDIA_API_KEY;
    const gemKey = process.env.GOOGLE_AI_API_KEY;

    // 1. Initialize NVIDIA Chat Client
    if (nvChatKey && nvChatKey !== 'your_nvidia_chat_key_here') {
      openai = new OpenAI({
        apiKey: nvChatKey.trim(),
        baseURL: 'https://integrate.api.nvidia.com/v1',
      });
      console.log('✅ NVIDIA NIM (Chat) initialized');
    }

    // 2. Initialize Google Gemini
    if (gemKey && gemKey !== 'AIzaSy_placeholder') {
      genAI = new GoogleGenerativeAI(gemKey.trim());
      geminiModel = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
      console.log('✅ Google Gemini initialized');
    }

    aiInitialized = !!(openai || geminiModel);
    return aiInitialized;
  } catch (error) {
    console.error('❌ AI Initialization Error:', error.message);
    return false;
  }
}

// Auto-run initialization
initializeAI();

/**
 * ARIZE PHOENIX TRACING
 */
async function traceAIInteraction(userId, message, context, response, latency, mood, provider) {
  try {
    const traceData = {
      trace_id: `trace_${Date.now()}_${userId}`,
      user_id: userId,
      input: message,
      context: context,
      output: response,
      latency_ms: latency,
      mood: mood?.label,
      provider: provider,
      timestamp: new Date().toISOString()
    };

    console.log(`[TRACE] AI Response generated by ${provider} in ${latency}ms`);
    await axios.post(`${PHOENIX_ENDPOINT}/v1/traces`, traceData).catch(() => { });
  } catch (err) {
    console.error('Tracing Error:', err.message);
  }
}

/**
 * PINECONE RAG RETRIEVAL
 * Uses NVIDIA_EMBED_API_KEY for vectorization.
 */
async function retrieveRAGContext(message) {
  try {
    const pcKey = process.env.PINECONE_API_KEY;
    const indexName = process.env.PINECONE_INDEX_NAME;
    const nvEmbedKey = process.env.NVIDIA_EMBED_API_KEY || process.env.NVIDIA_API_KEY;

    if (!pcKey || pcKey === 'your_pinecone_api_key_here' || !nvEmbedKey || nvEmbedKey === 'your_nvidia_embedding_key_here') {
      return null;
    }

    console.log('[RAG] Vectorizing query with NVIDIA Embedder...');
    
    // Create dedicated embedding client to use the specific embedding key
    const embedder = new OpenAI({
      apiKey: nvEmbedKey.trim(),
      baseURL: 'https://integrate.api.nvidia.com/v1',
    });

    const pc = new Pinecone({ apiKey: pcKey });
    const index = pc.index(indexName);

    const embResult = await embedder.embeddings.create({
      input: message,
      model: "nvidia/nv-embedqa-e5-v5",
      encoding_format: "float",
      input_type: "query",
      truncate: "NONE"
    });
    const vector = embResult.data[0].embedding;

    const queryResponse = await index.query({
      vector,
      topK: 6,
      includeMetadata: true
    });

    if (queryResponse.matches && queryResponse.matches.length > 0) {
      const relevantMatches = queryResponse.matches
        .filter(m => m.score > 0.6) // Lowered threshold slightly for better recall
        .sort((a, b) => b.score - a.score);

      if (relevantMatches.length === 0) return null;

      const groupedContext = relevantMatches.map(m => {
        return `[SOURCE: ${m.metadata.source || 'ChittSaathi KB'}] ${m.metadata.text}`;
      }).join('\n\n---\n\n');

      return {
        context: groupedContext,
        confidence: relevantMatches[0].score,
        sources: [...new Set(relevantMatches.map(m => m.metadata.source || m.metadata.title))]
      };
    }
  } catch (err) {
    console.error('RAG Retrieval Error:', err.message);
  }
  return null;
}

/**
 * SEMANTIC CRISIS DETECTION
 */
async function classifyEmotionUnlimited(input) {
  try {
    const pcKey = process.env.PINECONE_API_KEY;
    const indexName = process.env.PINECONE_INDEX_NAME;
    const nvEmbedKey = process.env.NVIDIA_EMBED_API_KEY || process.env.NVIDIA_API_KEY;

    if (!pcKey || !nvEmbedKey || nvEmbedKey.length < 10) return { isCrisis: false };

    const embedder = new OpenAI({
      apiKey: nvEmbedKey.trim(),
      baseURL: 'https://integrate.api.nvidia.com/v1',
    });

    const embResult = await embedder.embeddings.create({
      input: input,
      model: "nvidia/nv-embedqa-e5-v5",
      encoding_format: "float",
      input_type: "query",
      truncate: "NONE"
    });
    
    const pc = new Pinecone({ apiKey: pcKey });
    const index = pc.index(indexName);
    const queryResponse = await index.query({
      vector: embResult.data[0].embedding,
      topK: 3,
      filter: { dataset: { $in: ['indic', 'clpsych', 'goemotions'] } },
      includeMetadata: true
    });

    const crisisMatch = queryResponse.matches.find(m => 
      (m.metadata.category === 'crisis' || m.metadata.category === 'mental_health') && m.score > 0.82
    );

    return {
      isCrisis: !!crisisMatch,
      confidence: crisisMatch?.score || 0
    };
  } catch (err) {
    return { isCrisis: false };
  }
}

/**
 * ANALYZE FACE EMOTION (Bridge to ML Service)
 */
const analyzeFace = async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ success: false, message: 'No image file provided' });
    const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://localhost:8000/predict-face';
    
    const form = new FormData();
    form.append('file', req.file.buffer, { filename: req.file.originalname, contentType: req.file.mimetype });

    const response = await axios.post(ML_SERVICE_URL, form, {
      headers: { ...form.getHeaders() },
      timeout: 10000 
    });

    if (response.data && response.data.success) {
      const userId = req.user?.id;
      if (userId) {
        await new Mood({
          user: userId,
          value: response.data.mood,
          label: response.data.moodLabel,
          capturedVia: 'ai'
        }).save().catch(() => {});
      }
      return res.status(200).json({ ...response.data, saved: !!userId });
    }
    throw new Error('ML Service Error');
  } catch (error) {
    res.status(200).json({ success: true, mood: 4, moodLabel: 'Neutral', confidence: 0 });
  }
};

/**
 * GENERATE AI RESPONSE (Main Entry Point)
 * Implements 3-Tier Hybrid Architecture: Gemini -> NVIDIA -> Fallback
 */
const generateChatResponse = async (req, res) => {
  const startTime = Date.now();
  try {
    const { message, context, mood } = req.body;
    const userId = req.user?.id || 'anonymous';
    const sanitizedMessage = message.trim().substring(0, 2000);

    // 1. Safety Check (Keywords + Semantics)
    const semanticResult = await classifyEmotionUnlimited(sanitizedMessage);
    if (checkEmergencyKeywords(sanitizedMessage) || semanticResult.isCrisis) {
      const emergencyResponse = getEmergencyResponse();
      await saveConversation(userId, sanitizedMessage, emergencyResponse, 'emergency');
      return res.status(200).json({ success: true, response: emergencyResponse, type: 'emergency' });
    }

    // 2. RAG Retrieval
    const ragResult = await retrieveRAGContext(sanitizedMessage);
    const aiContext = prepareAIContext(sanitizedMessage, context, mood, ragResult?.context);

    // 3. Hybrid AI Pipeline
    let aiResponse;
    let aiProvider = 'hybrid-engine';

    try {
      // Tier 1: Gemini
      console.log('[AI] Trying Gemini P1...');
      aiResponse = await generateGeminiResponse(aiContext, sanitizedMessage);
      aiProvider = 'google-gemini';
    } catch (err) {
      console.warn('Gemini failed, trying NVIDIA NIM P2...');
      try {
        // Tier 2: NVIDIA NIM
        aiResponse = await generateNvidiaResponse(aiContext, sanitizedMessage);
        aiProvider = 'nvidia-nim';
      } catch (err2) {
        console.warn('NVIDIA failed, using Local Fallback P3...');
        // Tier 3: Hardened randomized empathy
        aiResponse = generateFallbackResponse(sanitizedMessage, mood);
        aiProvider = 'local-empathy';
      }
    }

    const finalResponse = applySafetyFilters(aiResponse);
    const latency = Date.now() - startTime;

    // Tracing & Persistence
    await traceAIInteraction(userId, sanitizedMessage, aiContext, finalResponse, latency, mood, aiProvider);
    await saveConversation(userId, sanitizedMessage, finalResponse, 'normal');

    res.status(200).json({
      success: true,
      response: finalResponse,
      type: aiProvider,
      latency: `${latency}ms`,
      rag: { used: !!ragResult, sources: ragResult?.sources || [] }
    });

  } catch (error) {
    console.error('AI Chat Error:', error);
    res.status(500).json({ success: false, message: 'Internal Server Error' });
  }
};

/**
 * GEMINI WORKER
 */
async function generateGeminiResponse(context, message) {
  if (!geminiModel) throw new Error('Gemini not ready');
  const result = await geminiModel.generateContent(context + "\n\nUser: " + message);
  return result.response.text();
}

/**
 * NVIDIA WORKER
 */
async function generateNvidiaResponse(context, message) {
  if (!openai) throw new Error('NVIDIA client not ready');
  const completion = await openai.chat.completions.create({
    model: "meta/llama-3.1-70b-instruct",
    messages: [
      { role: "system", content: context },
      { role: "user", content: message }
    ],
    temperature: 0.5,
    max_tokens: 1024,
  });
  return completion.choices[0]?.message?.content || "";
}

// Conversation Management
const getConversationHistory = async (req, res) => {
  try {
    const userId = req.user.id;
    const conversations = await Conversation.find({ user: userId }).sort({ createdAt: -1 }).limit(50);
    res.status(200).json({ success: true, conversations: conversations.reverse() });
  } catch (error) {
    res.status(500).json({ success: false, message: 'DB Error' });
  }
};

const clearConversationHistory = async (req, res) => {
  try {
    await Conversation.deleteMany({ user: req.user.id });
    res.status(200).json({ success: true, message: 'Cleared' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'DB Error' });
  }
};

// Helpers
function checkEmergencyKeywords(message) {
  const lowerMessage = message.toLowerCase();
  return EMERGENCY_KEYWORDS.some(k => lowerMessage.includes(k));
}

function getEmergencyResponse() {
  return `I'm very concerned about you. Your life matters deeply. Please reach out for help right now.

**24/7 Crisis Helplines:**
• **Vandrevala Foundation: 9152987821**
• **Emergency Services: 100**
• **AASRA: 9820466726**

You are not alone, and there is help available.`;
}

function prepareAIContext(message, context, mood, ragContext) {
  return `You are ChittSaathi AI, an empathetic mental health companion for students. 
Detected User Mood: ${mood?.label || 'Neutral'}
Previous History: ${context || 'None'}

${ragContext ? `TRUSTED CLINICAL DATA:\n${ragContext}\n` : ''}

GUIDELINES:
1. Speak as a warm, supportive peer/counselor.
2. Provide accurate, thoughtful, and comprehensive responses based on the clinical data.
3. If using clinical data, integrate it naturally and thoroughly.
4. Always acknowledge their current feelings.

User: "${message}"`;
}

function generateFallbackResponse(message, mood) {
  const pools = [
    "I'm here for you. It sounds like you're going through a lot, and I want you to know I'm listening.",
    "Thank you for sharing that with me. Your feelings are completely valid. How can I best support you right now?",
    "That sounds challenging. Focusing on one small step at a time can often help. I'm right here with you.",
    "I'm listening and I hear how you're feeling. You don't have to carry this alone."
  ];
  return pools[Math.floor(Math.random() * pools.length)];
}

function applySafetyFilters(response) {
  if (HARMFUL_CONTENT.some(h => response.toLowerCase().includes(h))) {
    return "I want to support you safely. If you're feeling overwhelmed, please speak to a trusted mentor or professional.";
  }
  return response;
}

async function saveConversation(userId, userMessage, aiResponse, type) {
  await new Conversation({ user: userId, userMessage, aiResponse, type }).save().catch(() => {});
}

module.exports = {
  generateChatResponse,
  getConversationHistory,
  clearConversationHistory,
  analyzeFace
};
