const Conversation = require('../models/Conversation');
const { OpenAI } = require('openai');
const { Pinecone } = require('@pinecone-database/pinecone');
const axios = require('axios');

// Initialize Arize Phoenix Global Config
const PHOENIX_ENDPOINT = process.env.PHOENIX_COLLECTOR_ENDPOINT || 'http://localhost:6006';

// Safety filter keywords
const EMERGENCY_KEYWORDS = [
  'suicide', 'kill myself', 'end my life', 'want to die', 'self harm', 'hurt myself',
  'cut myself', 'overdose', 'jump off', 'hang myself', 'not worth living',
  'better off dead', 'end it all', 'can\'t go on', 'taking my life',
  '108', '104', '112', 'ambulance', 'pcr'
];

const HARMFUL_CONTENT = [
  'violence', 'self-medication', 'illegal drugs', 'alcohol abuse'
];

// Initialize NVIDIA NIM via OpenAI Interface
let openai = null;
let aiInitialized = false;

// Function to initialize AI service with better error handling
function initializeAI() {
  try {
    const nvKey = process.env.NVIDIA_API_KEY;

    console.log('Checking NVIDIA API Key...');
    console.log('API Key exists:', !!nvKey);
    console.log('API Key preview:', nvKey ? `${nvKey.substring(0, 10)}...` : 'No key found');

    if (!nvKey || nvKey === 'your_nvidia_nim_api_key_here') {
      console.warn('🚨 No NVIDIA API key provided. AI responses will use fallback mode.');
      return false;
    }

    openai = new OpenAI({
      apiKey: nvKey.trim(),
      baseURL: 'https://integrate.api.nvidia.com/v1',
    });
    console.log('✅ NVIDIA NIM initialized successfully with API key');
    return true;
  } catch (error) {
    console.error('❌ Failed to initialize NVIDIA NIM:', error.message);
    return false;
  }
}

// Initialize on startup
aiInitialized = initializeAI();

/**
 * ARIZE PHOENIX TRACING
 * Logs the AI interaction and sends it to the Phoenix collector.
 */
async function traceAIInteraction(userId, message, context, response, latency, mood, provider) {
  try {
    const traceData = {
      trace_id: `trace_${Date.now()}_${userId}`,
      user_id: userId,
      input: message,
      context: context,
      output: response,
      latency_ms: latency,
      mood: mood?.label,
      provider: provider,
      timestamp: new Date().toISOString()
    };

    // Log locally
    console.log(`[TRACE] AI Response generated by ${provider} in ${latency}ms`);

    // Send to Phoenix (Optional - fails silently if collector is down)
    await axios.post(`${PHOENIX_ENDPOINT}/v1/traces`, traceData).catch(() => { });
  } catch (err) {
    console.error('Tracing Error:', err.message);
  }
}

/**
 * PINECONE RAG RETRIEVAL
 * Searches the knowledge base for top-k relevant fragments.
 */
async function retrieveRAGContext(message) {
  try {
    const pcKey = process.env.PINECONE_API_KEY;
    const indexName = process.env.PINECONE_INDEX_NAME;

    if (!pcKey || pcKey === 'your_pinecone_api_key_here') return null;

    const pc = new Pinecone({ apiKey: pcKey });
    const index = pc.index(indexName);

    // 1. Vectorize the User Question using NVIDIA NIM
    const embResult = await openai.embeddings.create({
      input: message,
      model: "nvidia/nv-embedqa-e5-v5",
      encoding_format: "float",
      input_type: "query",
      truncate: "NONE"
    });
    const vector = embResult.data[0].embedding;

    // 2. Query Pinecone with higher topK for diversity
    const queryResponse = await index.query({
      vector,
      topK: 6,
      includeMetadata: true
    });

    if (queryResponse.matches && queryResponse.matches.length > 0) {
      // Hyper-Optimization: Filter by score threshold (0.7) and sort
      const relevantMatches = queryResponse.matches
        .filter(m => m.score > 0.7)
        .sort((a, b) => b.score - a.score);

      if (relevantMatches.length === 0) return null;

      const bestMatch = relevantMatches[0];
      
      // Group by Source for cleaner LLM injection
      const groupedContext = relevantMatches.map(m => {
        const sourceName = m.metadata.source || m.metadata.title || 'ChittSaathi KB';
        return `[SOURCE: ${sourceName} (Relevance: ${Math.round(m.score * 100)}%)] ${m.metadata.text}`;
      }).join('\n\n---\n\n');

      return {
        context: groupedContext,
        confidence: bestMatch.score,
        sources: [...new Set(relevantMatches.map(m => m.metadata.source || m.metadata.title))]
      };
    }
  } catch (err) {
    console.error('RAG Retrieval Error:', err.message);
  }
  return null;
}

async function classifyEmotionUnlimited(input) {
  try {
    const pcKey = process.env.PINECONE_API_KEY;
    const indexName = process.env.PINECONE_INDEX_NAME;
    if (!pcKey || pcKey === 'your_pinecone_api_key_here') return { isCrisis: false };

    // 1. Clean + Emoji Translation (Hackathon Feature)
    const emojiMap = { '😢': 'sadness', '💔': 'heartbreak', '😞': 'distress', '🆘': 'emergency', '🔪': 'harm' };
    let cleanInput = input.toLowerCase();
    Object.keys(emojiMap).forEach(e => cleanInput = cleanInput.replace(new RegExp(e, 'g'), ` ${emojiMap[e]} `));

    // 2. Embed using NVIDIA NIM
    const embResult = await openai.embeddings.create({
      input: cleanInput,
      model: "nvidia/nv-embedqa-e5-v5",
      encoding_format: "float",
      input_type: "query",
      truncate: "NONE"
    });
    const vector = embResult.data[0].embedding;

    // 3. Pinecone Search across specific critical datasets (INDIC, CLPsych, GoEmotions)
    const pc = new Pinecone({ apiKey: pcKey });
    const index = pc.index(indexName);
    const queryResponse = await index.query({
      vector,
      topK: 5,
      filter: { dataset: { $in: ['indic', 'clpsych', 'goemotions'] } },
      includeMetadata: true
    });

    // 4. Threshold Logic: Trigger if highest match is 'crisis' or from specific datasets
    const INDIC_CRISIS_PHRASES = ['जीना नहीं चाहता', 'मरना चाहता हूँ', 'आत्महत्या', 'not worth living', '108', '104'];
    const hasIndicCrisis = INDIC_CRISIS_PHRASES.some(p => input.includes(p));

    const crisisMatch = queryResponse.matches.find(m => 
      (m.metadata.category === 'crisis' || 
       m.metadata.category === 'mental_health' || 
       m.metadata.source?.includes('CLPsych') || 
       m.metadata.source?.includes('Indic')) && 
      m.score > (hasIndicCrisis ? 0.70 : 0.82)
    );

    const sourceTags = [...new Set(queryResponse.matches.slice(0, 2).map(m => `[${m.metadata.source || m.metadata.title}]`))].join(' + ');

    return {
      isCrisis: !!crisisMatch || hasIndicCrisis,
      confidence: crisisMatch?.score || (hasIndicCrisis ? 0.95 : 0),
      status: `High conf ${sourceTags}`,
      dominantCategory: queryResponse.matches[0]?.metadata?.category
    };
  } catch (err) {
    console.error('Semantic Analysis Error:', err.message);
    return { isCrisis: false };
  }
}

// @desc    Generate AI chat response
// @route   POST /api/ai/chat
// @access  Private
const generateChatResponse = async (req, res) => {
  const startTime = Date.now();
  try {
    const { message, context, mood } = req.body;
    const userId = req.user?.id || 'anonymous';

    // 1. Validate and Sanitize Input
    if (!message || typeof message !== 'string' || message.trim().length === 0) {
      return res.status(400).json({ success: false, message: 'Message content is required' });
    }

    // 2. Prevent payload abuse
    const sanitizedMessage = message.trim().substring(0, 2000);
    console.log(`[AI Request] User: ${userId} | Mood: ${mood?.label || 'N/A'}`);

    // --- PHASE 3: UNLIMITED SEMANTIC CRISIS DETECTION ---
    const semanticResult = await classifyEmotionUnlimited(sanitizedMessage);
    const isCrisis = checkEmergencyKeywords(sanitizedMessage) || semanticResult.isCrisis;
    
    console.log(`[Safety] Semantic Check: ${semanticResult.status} | Score: ${semanticResult.confidence}`);

    if (isCrisis) {
      console.log('🚨 SEMANTIC CRISIS DETECTED! Confidence:', semanticResult.confidence);
      const emergencyResponse = getEmergencyResponse();
      await saveConversation(userId, sanitizedMessage, emergencyResponse, 'emergency');
      return res.status(200).json({ 
        success: true, 
        response: emergencyResponse, 
        type: 'emergency',
        semanticConfidence: semanticResult.confidence
      });
    }

    // --- PHASE 2: RAG DATA RETRIEVAL ---
    console.log('Retrieving RAG context...');
    const ragResult = await retrieveRAGContext(sanitizedMessage);
    const ragContext = ragResult?.context || null;

    // --- PHASE 1: PREPARE PROMPT ---
    const aiContext = prepareAIContext(sanitizedMessage, context, mood, ragContext);

    let aiResponse;
    let aiProvider = 'nvidia-nim';

    try {
      aiResponse = await generateNvidiaResponse(aiContext, sanitizedMessage);
    } catch (aiError) {
      console.warn('NVIDIA NIM failed, trying Gemma Fallback...');
      try {
        aiResponse = await generateGemmaFallback(aiContext, sanitizedMessage);
        aiProvider = 'gemma';
      } catch (gemmaError) {
        aiResponse = generateFallbackResponse(sanitizedMessage, mood);
        aiProvider = 'rule-based';
      }
    }

    let safeResponse = applySafetyFilters(aiResponse);
    
    // --- PHASE 4: RAG CITATIONS ---
    if (aiProvider === 'nvidia-nim' && ragResult && ragContext) {
      const confidencePercent = Math.round((ragResult.confidence || 0) * 100);
      const sourcesStr = (ragResult.sources || []).join(', ');
      safeResponse += `\n\n📚 Sources: [${sourcesStr || 'ChittSaathi KB'}] | Confidence: ${confidencePercent}%`;
    }

    const latency = Date.now() - startTime;

    // --- PHASE 2: ARIZE TRACING ---
    await traceAIInteraction(userId, sanitizedMessage, aiContext, safeResponse, latency, mood, aiProvider);

    await saveConversation(userId, sanitizedMessage, safeResponse, 'normal');

    res.status(200).json({
      success: true,
      response: safeResponse,
      type: aiProvider,
      mood: mood?.label || null,
      latency: `${latency}ms`,
      rag: {
        used: !!ragContext,
        confidence: ragContext?.confidence >= 0.7 ? "High" : "Standard",
        sources: ragContext?.sources || []
      }
    });

  } catch (error) {
    console.error('AI Chat Error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate response' });
  }
};

// @desc    Get conversation history
// @route   GET /api/ai/conversation
// @access  Private
const getConversationHistory = async (req, res) => {
  try {
    const userId = req.user.id;
    const limit = parseInt(req.query.limit) || 50;

    const conversations = await Conversation.find({ user: userId })
      .sort({ createdAt: -1 })
      .limit(limit)
      .select('userMessage aiResponse type createdAt');

    res.status(200).json({
      success: true,
      conversations: conversations.reverse() // Return in chronological order
    });

  } catch (error) {
    console.error('Get Conversation Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve conversation history'
    });
  }
};

// @desc    Clear conversation history
// @route   DELETE /api/ai/conversation
// @access  Private
const clearConversationHistory = async (req, res) => {
  try {
    const userId = req.user.id;

    await Conversation.deleteMany({ user: userId });

    res.status(200).json({
      success: true,
      message: 'Conversation history cleared successfully'
    });

  } catch (error) {
    console.error('Clear Conversation Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to clear conversation history'
    });
  }
};

// Helper Functions

function checkEmergencyKeywords(message) {
  const lowerMessage = message.toLowerCase();
  return EMERGENCY_KEYWORDS.some(keyword => lowerMessage.includes(keyword));
}

function getEmergencyResponse() {
  return `I'm very concerned about what you've shared. Your life has value and there are people who want to help you right now.

**Immediate Support:**
• **Crisis Helpline: 9152987821** (Available 24/7)
• **Emergency Services: 100**
• **AASRA: 022-27546669** (24x7 Suicide Prevention)

Please reach out to someone you trust or use one of these resources immediately. You are not alone, and there are people who care about you and want to help.

If you're in immediate danger, please call emergency services or go to your nearest hospital emergency room.`;
}

function prepareAIContext(message, context, mood, ragContext) {
  let aiContext = `You are ChittSaathi AI Assistant, a supportive mental health companion for students. 
Your goal is to provide a safe, empathetic space.

USER CONTEXT:
- Detected Emotion (via Face ML): ${mood?.label || 'Unknown'} (Confidence: ${mood?.confidence ? (mood.confidence * 100).toFixed(1) + '%' : 'N/A'})
- Previous Context: ${context || 'None'}

${ragContext ? `### TRUSTED KNOWLEDGE BASE (STRICT AUTHORITY):
The following information is retrieved from our clinical datasets (DAIR.AI, GoEmotions, Indic, CLPsych). 
You MUST prioritize this over your general knowledge for technical terms or campus resources.

${ragContext}
` : ''}

CORE GUIDELINES:
1. Empathy Foundation: Start every response by acknowledging the user's emotional state.
2. Tone: Warm, supportive academic counselor (NOT clinical/robotic).
3. Length: 3-5 high-impact sentences.
4. Citation: If you use the TRUSTED KNOWLEDGE, do not mention "The knowledge base says..." but speak naturally.
5. Missing info: If the user asks for something not in TRUSTED KNOWLEDGE, provide standard supportive listening.

Current Student Message: "${message}"

Write your supportive response:`;

  return aiContext;
}

/**
 * GEMMA FALLBACK (P1 Architecture)
 * Attempts to connect to a local Gemma instance if Gemini fails.
 */
async function generateGemmaFallback(context, message) {
  const gemmaUrl = process.env.OLlama_URL || 'http://localhost:11434/api/generate';

  try {
    const response = await axios.post(gemmaUrl, {
      model: "gemma2:2b",
      prompt: context + "\n" + message,
      stream: false
    }, { timeout: 7000 });

    return response.data.response;
  } catch (error) {
    throw new Error('Gemma Service Unavailable');
  }
}

async function generateNvidiaResponse(context, message) {
  if (!aiInitialized || !openai) {
    throw new Error('NVIDIA NIM service not available');
  }

  const maxRetries = 3;
  let lastError;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`Sending request to NVIDIA NIM API (Attempt ${attempt}/${maxRetries})...`);
      
      const completion = await openai.chat.completions.create({
        model: "nvidia/llama-3.1-nemotron-70b-instruct",
        messages: [
          { role: "system", content: context },
          { role: "user", content: message }
        ],
        temperature: 0.5,
        max_tokens: 1024,
      });

      const text = completion.choices[0]?.message?.content;
      if (text && text.trim()) return text.trim();
      throw new Error('Empty response from NVIDIA NIM');

    } catch (error) {
      lastError = error;
      console.error(`❌ Attempt ${attempt} Failed:`, error.message);
      
      if (attempt < maxRetries) {
        const delay = Math.pow(2, attempt) * 500; // Exponential backoff: 1s, 2s, 4s
        console.log(`Retrying in ${delay}ms...`);
        await new Promise(res => setTimeout(res, delay));
      }
    }
  }

  // Final catch-all: Try standard Llama 3.1 70b via NIM before failing to non-NVIDIA fallback
  try {
    console.log('Trying standard meta/llama-3.1-70b-instruct as emergency NVIDIA fallback...');
    const fallback = await openai.chat.completions.create({
      model: "meta/llama-3.1-70b-instruct",
      messages: [{ role: "system", content: context }, { role: "user", content: message }],
      max_tokens: 1024
    });

    if (fallback.choices[0]?.message?.content) {
      return fallback.choices[0].message.content.trim();
    }
    throw new Error('Emergency NVIDIA fallback failed');
  } catch (e) {
    throw lastError || e; 
  }
}




function generateFallbackResponse(message, mood) {
  const lowerMessage = message.toLowerCase();

  // Mood-based responses
  if (mood && mood.label) {
    switch (mood.label.toLowerCase()) {
      case 'sad':
        return "I understand you're feeling sad right now. These feelings are valid and temporary. Consider talking to someone you trust, doing something that brings you comfort, or engaging in gentle physical activity. Remember, this feeling will pass. What usually helps you feel better when you're sad?";

      case 'angry':
        return "I can sense you're feeling angry. That's a natural emotion. Try taking deep breaths, going for a walk, or writing down your thoughts. Physical exercise can help release that energy. What's causing you to feel this way?";

      case 'fear':
      case 'anxious':
        return "Anxiety can feel overwhelming, but you're not alone. Try the 4-7-8 breathing technique: breathe in for 4, hold for 7, exhale for 8. Ground yourself by naming 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, and 1 you can taste. What's making you feel anxious?";

      case 'happy':
        return "It's wonderful that you're feeling good! I notice you mentioned feeling anxious despite being in a happy mood - sometimes we can feel multiple emotions at once, and that's completely normal. Try some deep breathing exercises or grounding techniques. Would you like to share what's causing the anxiety?";

      default:
        return "Thank you for sharing with me. I'm here to listen and support you. Whatever you're going through, your feelings are valid. Sometimes talking helps us process our emotions better. What would you like to talk about?";
    }
  }

  // Keyword-based responses for anxiety and overwhelm
  if (lowerMessage.includes('anxious') || lowerMessage.includes('anxiety')) {
    return "I hear that you're feeling anxious, and I want you to know that these feelings are completely valid. Anxiety can be overwhelming, but there are effective ways to manage it. Try some deep breathing exercises - breathe in for 4 counts, hold for 4, and exhale for 4. Grounding techniques can also help: name 5 things you can see, 4 you can touch, 3 you can hear. What's been contributing to your anxiety lately?";
  }

  if (lowerMessage.includes('overwhelm') || lowerMessage.includes('stressed')) {
    return "Feeling overwhelmed is really tough, and I'm glad you're reaching out. When everything feels like too much, try breaking things down into smaller, manageable pieces. Focus on just the next small step you can take. Remember to breathe deeply and give yourself permission to take breaks. You don't have to handle everything at once. What's been the biggest source of stress for you recently?";
  }

  if (lowerMessage.includes('lonely') || lowerMessage.includes('alone')) {
    return "Feeling lonely is difficult, but you're not alone in experiencing this. Consider reaching out to friends, family, or joining activities that interest you. Sometimes even small social interactions can help. Is there someone you feel comfortable talking to?";
  }

  if (lowerMessage.includes('study') || lowerMessage.includes('exam') || lowerMessage.includes('academic')) {
    return "Academic pressure is real and challenging. Try creating a study schedule, taking regular breaks, and using techniques like the Pomodoro method. Remember, your worth isn't defined by grades. What specific academic challenge are you facing?";
  }

  // General supportive response
  const supportiveResponses = [
    "I hear you, and I'm here to support you. Your feelings are valid, and reaching out shows strength. When we're feeling anxious and overwhelmed, it can help to focus on what we can control right now. What's been weighing on your mind the most?",
    "Thank you for trusting me with your thoughts. Feeling anxious and overwhelmed is really challenging, but you're taking a positive step by talking about it. Sometimes just expressing these feelings can provide some relief. What would be most helpful for you right now?",
    "I understand this might be a difficult time for you. Anxiety and feeling overwhelmed are common experiences, especially for students. You're not alone in this. Consider practicing some mindfulness or reaching out to someone you trust. What's been the main source of these feelings?",
    "Your wellbeing matters, and I'm glad you're here to talk. When anxiety and overwhelm hit, it's important to be gentle with yourself. Try to focus on your breathing and remember that these intense feelings will pass. What specific situation is making you feel this way?"
  ];

  return supportiveResponses[Math.floor(Math.random() * supportiveResponses.length)];
}

function applySafetyFilters(response) {
  // Check for harmful content
  const lowerResponse = response.toLowerCase();

  // Filter out medical diagnoses
  const medicalTerms = ['diagnose', 'diagnosis', 'disorder', 'medication', 'prescription', 'cure', 'treatment'];
  const containsMedical = medicalTerms.some(term => lowerResponse.includes(term));

  if (containsMedical) {
    return "I understand you're looking for help, but I can't provide medical advice or diagnoses. I encourage you to speak with a healthcare professional, counselor, or trusted adult who can provide proper guidance. In the meantime, I'm here to listen and offer emotional support.";
  }

  // Filter harmful content
  const containsHarmful = HARMFUL_CONTENT.some(term => lowerResponse.includes(term));

  if (containsHarmful) {
    return "I want to make sure I'm providing you with safe and helpful support. Sometimes it's best to talk with a trained counselor who can provide more specific guidance. I'm here to listen and offer emotional support in the meantime.";
  }

  return response;
}

async function saveConversation(userId, userMessage, aiResponse, type = 'normal') {
  try {
    const conversation = new Conversation({
      user: userId,
      userMessage,
      aiResponse,
      type,
      metadata: {
        timestamp: new Date(),
        responseLength: aiResponse.length
      }
    });

    await conversation.save();
    console.log('Conversation saved successfully');
  } catch (error) {
    console.error('Save Conversation Error:', error);
  }
}

module.exports = {
  generateChatResponse,
  getConversationHistory,
  clearConversationHistory,
  classifyEmotionUnlimited,
  retrieveRAGContext
};
